rk: ANDROID: rwsem: Fix compilation error when CONFIG_PREEMPT_RT
kernel/locking/rwsem.c:1711:2: error: call to undeclared function 'trace_android_vh_rwsem_write_finished'; [-Wimplicit-function-declaration]
kernel/locking/rwsem.c:1722:2: error: call to undeclared function 'trace_android_vh_rwsem_write_finished'; [-Wimplicit-function-declaration]

Fixes: 78cf7a145c20 ("ANDROID: rwsem: Add vendor hook to the rw-semaphore")
Change-Id: I9062aef1138055e47cd6824892b291d5a66892dc
Signed-off-by: Tao Huang <huangtao@rock-chips.com>