arm64: rockchip_defconfig: Enable CONFIG_F2FS_UNFAIR_RWSEM
According to GKI commit 70723dd2ed4b ("ANDROID: gki_config: enable F2FS_UNFAIR_RWSEM").

Fix the following compile error:
In file included from fs/f2fs/gc.c:19:
fs/f2fs/f2fs.h:2194:42: error: no member named 'read_waiters' in 'struct f2fs_rwsem'
 2194 |         _trace_android_rvh_f2fs_down_read(&sem->read_waiters, &sem->internal_rwsem, &skip);

Change-Id: I4f03c17061b26017d126a44be93502d4c4567234
Signed-off-by: Tao Huang <huangtao@rock-chips.com>